content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields:
      - name: tweet
        label: Tweet
        type: text
        options:
        maxlength: 140
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file
    fields: